### ISSUE TITLE
Installer doing nothing

### ISSUE THREAD

**Issue by Sadzeih** [symfony/symfony-installer#151] opened 2015-04-29 09:06 UTC
Hello,

I'm starting Symfony just now, I wanted to install it via the installer, it seemed easy. There's a problem though.

I'm installing it via curl and changing the permissions on the file. When I launch it with this command:
```
symfony new project
```
It just does nothing.

**Comment by Pierstoval** [comment] 2015-04-29 09:18
Do you have the right permissions on the working directory?
 
Can you run the symfony command using the `-vvv` option to see if there's any other output?

**Comment by Sadzeih** [comment] 2015-04-29 09:32
I do have the permissions on the working directory:
```
total 12
drwxrwxr-x  2 guervi_a users 4096 Apr 29 11:31 .
drwx-----x 45 guervi_a users 4096 Apr 29 11:09 ..
-rw-r--r--  1 guervi_a users   20 Apr 27 18:24 index.php
```

I ran ```symfony -vvv new project``` and still nothing.

**Comment by Pierstoval** [comment] 2015-04-29 09:33
What with a `sudo`? I have no idea of what could be going on actually :confused:

**Comment by Sadzeih** [comment] 2015-04-29 09:33
Nope nothing.

**Comment by javiereguiluz** [comment] 2015-04-29 09:36
@Sadzeih I have three quick questions for you: which operating system / version are you using? Are you using any virtualization tool such as Vagrant? Do you use a proxy server to access the Internet?

**Comment by Sadzeih** [comment] 2015-04-29 09:39
@javiereguiluz I'm using Manjaro (3.16 Linux Kernel) 64 bits. It's not a virtual machine, no. I'm at school, but I don't think there is any proxy since I've never encountered any problem with installations.

**Comment by Pierstoval** [comment] 2015-04-29 09:42
There may be a proxy filtering some addresses. Schools often expectedly have some firewalls :p 
 
Can you try to download the phar file directly from your browser with [this link](https://symfony.com/installer)? After that, just run the phar file and check if the behavior is different.

**Comment by Sadzeih** [comment] 2015-04-29 09:46
I'm not in a usual school (developping school), there isn't any firewall of such. The internet here is completely open so that's why I guess there no proxy filtering.
I downloaded the .phar directly from the website and same behavior.

**Comment by javiereguiluz** [comment] 2015-04-29 09:47
About the actual error: the command ends just after executing it?  Or does the command waits indefinitely without outputing anything on the screen?

**Comment by Pierstoval** [comment] 2015-04-29 09:50
Can you run the command like this : `symfony list ; echo $?` to check what is the exit code? (don't know, it's a mystery, we can check anything)

**Comment by Sadzeih** [comment] 2015-04-29 09:52
The command just executes but does nothing apparently. 0 is the exit code.

**Comment by Pierstoval** [comment] 2015-04-29 09:53
What about Composer?

**Comment by Sadzeih** [comment] 2015-04-29 09:54
With composer I did get a result. It downloaded the project but when I did ```php app/console server:run``` I had a error about timezone, don't know what it was though.

**Comment by Pierstoval** [comment] 2015-04-29 09:56
For the timezone option, it's a configuration issue, run `php --ini` to check which INI file is the main configuration for php, and check that the `date.timezone` php.ini configuration option is set to your timezone (certainly `Europe/Paris` for you).

**Comment by javiereguiluz** [comment] 2015-04-29 09:56
@Sadzeih to check if there is a problem with all the Symfony console commands, please do the following:

1. Download the `http://symfony.com/download?v=Symfony_Standard_Vendors_latest.zip` file
2. Uncompress it anywhere.
3. Enter in the uncompressed directory and execute: `php app/console`

Let us know if you see something in the console window. Thanks.

**Comment by Pierstoval** [comment] 2015-04-29 09:57
@javiereguiluz It seems that Composer works properly, so I think it's not an issue with Symfony console commands. Or it might be an issue to one potential installer's behavior that is not used by Composer :confused:

**Comment by javiereguiluz** [comment] 2015-04-29 09:58
@Pierstoval maybe it's a problem of the Guzzle progress bar and the command is working without outputting anything on the screen.

**Comment by Pierstoval** [comment] 2015-04-29 09:59
@Sadzeih You could also try to clone the installer's git repo in your local env, install composer dependencies with a `composer install` and then run `./symfony` to see if it comes from the phar file or from the installer "itself".

**Comment by Sadzeih** [comment] 2015-04-29 10:17
Ok so I cloned the repo and ```composer install```ed and it worked. It seem that the .phar from your website is bugged or something but now it definitely works. Thank you!

**Comment by Pierstoval** [comment] 2015-04-29 10:18
It'd be the best if you could `box` the installer manually to see the differences between the phar you downloaded and the phar generated by box :)

**Comment by Sadzeih** [comment] 2015-04-29 10:19
What do you mean by box?

**Comment by Pierstoval** [comment] 2015-04-29 10:20
The phar file is generated with [Box](http://box-project.org/) , a small app that can generate phars based on a little `box.json` conf file :)

**Comment by javiereguiluz** [comment] 2015-04-29 10:21
@Sadzeih we use `box` to generate the installer PHAR file. If you want to create the installer PHAR for yourself, execute the following:

```bash
$ curl -LSs https://box-project.github.io/box2/installer.php | php
$ cd symfony-installer/
$ box build
```

**Comment by javiereguiluz** [comment] 2015-04-29 10:22
@Pierstoval the problem may be in the fact that we compress the installer PHAR file. Maybe the PHP or operating system used by @Sadzeih doesn't support that feature. If that's the case, we should not compress the installer's PHAR, because anyway it's not that big.

**Comment by Pierstoval** [comment] 2015-04-29 11:31
Yup, I think that compressing it may be wrong in some cases, but IMO, if the user has a wrong config, it should be his responsibility?
It's not like file's integrity have ever been debated :laughing:

**Comment by javiereguiluz** [comment] 2015-05-18 07:38
Closing it for now because there seems to be nothing else we can do in this case. We'll be on alert if any other user reports the same problem in the future. Thanks.

**Closed by javiereguiluz** 2015-05-18 07:38 UTC
Labels: bug, unconfirmed

**Comment by ramyx** [comment] 2015-06-01 08:20
Hello. I had the same problem in manjaro distro, following the thread I could solve it by doing the following:
$ yaourt -S php-box php-composer
$ git clone https://github.com/symfony/symfony-installer.git
$ cd symfony-installer/
$ composer install
$ php-box build
$ sudo mv symfony.phar /usr/share/webapp/bin/symfony
$ sudo ln -s /usr/share/webapp/bin/symfony /usr/local/bin

Details in my blog http://goo.gl/7d9eEa (spanish)
Here is mi phar file https://goo.gl/pDBfe3

I hope this information can help, regards.

**Comment by jamalsa** [comment] 2015-07-23 10:12
I ran into the same problem today (on ArchLinux x86_64) and found the cause:

1. Phar extension is not enabled by default. You can enable this in php.ini (in Arch and Manjaro its located at /etc/php/php.ini) by remove leading semicolon in ;extension=phar.so.

2. /usr/local/bin/symfony is not in open_basedir. Add it in php.ini.

After I updated php.ini the installer is worked perfectly. Hope this help.

**Comment by jamalsa** [comment] 2015-07-23 10:14
@javiereguiluz maybe this information should be added to the readme/ Symfony documentation. If you agree I can make a pull request about it.

**Comment by xabbuh** [comment] 2015-07-23 22:25
@jamalsa I think adding some general troubleshooting information is a good idea.

**Comment by jamalsa** [comment] 2015-07-24 04:03
After I gave another thought, isn't it better if the installer failed if phar extension is disabled and open_basedir not configured properly? This way user will know what happening without reading documentation.

**Comment by javiereguiluz** [comment] 2015-07-24 15:12
@jamalsa I agree with your last comment. I think this is something we can check automatically. I've create a new issue in #179 to implement that feature. Thanks!
