### ISSUE TITLE
The selected version (latest) cannot be installed because it does not exist

### ISSUE THREAD

**Issue by yrssoft** [symfony/symfony-installer#141] opened 2015-04-10 02:49 UTC
[RuntimeException]                                                            
  The selected version (latest) cannot be installed because it does not exist.  
  Execute the following command to install the latest stable Symfony release:   
  /usr/local/bin/symfony new /home/yrssoft/symfony

**Comment by javiereguiluz** [comment] 2015-04-10 18:46
@yrssoft thanks for reporting this issue. Sadly, I cannot reproduce this problem in any way. I guess you have executed the command without a version constraint (.e.g `symfony new my_project`) because then the installer uses the special `latest` version name. And that version is provided by symfony.com server. I've checked it again and it seems to work as expected.

My guess is that either a temporary symfony.com error prevented to get the `latest` special version or another error happen and then, the error message is wrong. @yrssoft could you please try to update the installer to the latest version (`symfony self-update`) and then execute it again with and without a version constraint (e.g. `symfony new my_project` and `symfony new my_project 2.6`)

**Comment by javiereguiluz** [comment] 2015-04-22 13:02
@yrssoft did you finally manage to install Symfony? Or do you still get this error message?

**Comment by javiereguiluz** [comment] 2015-04-29 10:12
Closing it becase there is no more feedback and I cannot reproduce it. If the error still persist, please feel free to reopening it. Thanks!

**Closed by javiereguiluz** 2015-04-29 10:12 UTC
Labels: bug, unconfirmed

**Comment by SakyaStelios** [comment] 2015-10-20 15:23
Same issue running behind a proxy in Windows 7. 

I have a enviroment variable called HTTP_PROXY. When I delete it, the installer works.

**Comment by xabbuh** [comment] 2015-10-20 18:03
@SakyaStelios which version of the installer do you use?

**Comment by javiereguiluz** [comment] 2015-10-20 18:09
@SakyaStelios the described behavior is strange because we copied the code from Composer.

**Comment by SakyaStelios** [comment] 2015-10-20 19:55
I have the last version of the installer.

**Comment by modiniks** [comment] 2017-11-14 04:56
I have the latest version of the installer downloaded today.

[RuntimeException]
  The selected version (3.3.12) cannot be installed because it does not exist.
  Execute the following command to install the latest stable Symfony release:
  symfony new apidemo

**Comment by AnatolyMuntean** [comment] 2017-11-14 08:02
Looks like it tries to download latest release marked as the v3.3.12, but checked the repo and there is no v3.3.12 tag.
`symfony new APP_NAME 3.3.11` works though.

**Comment by YacineKhamis** [comment] 2017-11-14 09:00
Same here. @AnatolyMuntean thank you ! Trying with appending 3.3.11 at the end works !

**Comment by SHAdaVinci** [comment] 2017-11-15 08:48
try verbose/debug:
```bash
symphony new APP_NAME -vvv
```
it shows everything - installer:
1. gets version list (from https://symfony.com/versions.json)
2. builds URL (by default download version ```latest``` from versions.json) - for 3.3.12 it is https://symfony.com/download?v=Symfony_Standard_Vendors_3.3.12.tgz
3. builded URL redirects (302) to https://get.symfony.com/Symfony_Standard_Vendors_3.3.12.tgz
4. redirected URL returns Forbidden (403) error: Access Denied
(BTW: it downloads ok for version 3.3.11)

which is displayed by installer as error "The selected version (3.3.12) cannot be installed because it does not exist."

@javiereguiluz could you pass question to (get.)symfony.com site maintainer if version 3.3.12 is available for download?

**Comment by yahuarkuntur** [comment] 2017-11-15 20:13
The error for me is as follows:

````
$ symfony new factureasy-php 2.8

[RuntimeException]                                                            
  The selected version (2.8.30) cannot be installed because it does not exist.  
  Execute the following command to install the latest stable Symfony release:   
  /usr/local/bin/symfony new factureasy-php   

Symfony Installer version 1.5.9

````

**Comment by vladciulley** [comment] 2017-11-16 15:00
Same here!

```
$ symfony new test_project

 Downloading Symfony...

  [RuntimeException]
  The selected version (3.3.12) cannot be installed because it does not exist.
  Execute the following command to install the latest stable Symfony release:
  /usr/local/bin/symfony new test_project
```

Using specific 3.3.11 version works fine, but still, I also tried:

```
$ symfony new test_project lts

 Downloading Symfony...

  [RuntimeException]
  The selected version (2.8.30) cannot be installed because it does not exist.
  Execute the following command to install the latest stable Symfony release:
  /usr/local/bin/symfony new test_project
```
I don't know how it gets the latest version or the LTS version, but something is wrong.

**Comment by kum1ko** [comment] 2017-11-17 02:13
Same problem.
Your server returned "HTTP/1.1 403 Forbidden (https://get.symfony.com/Symfony_Standard_Vendors_2.8.30.tgz)

**Comment by kniziol** [comment] 2017-12-22 07:58
@javiereguiluz @SHAdaVinci 
Same problem here. More information while using `-vvv` option:
```bash
* Connection #0 to host symfony.com left intact
* Hostname get.symfony.com was found in DNS cache
*   Trying 52.84.194.185...
* TCP_NODELAY set
* Connected to get.symfony.com (52.84.194.185) port 443 (#1)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.symfony.com
* Server certificate: Gandi Standard SSL CA 2
* Server certificate: USERTrust RSA Certification Authority
> GET /Symfony_Standard_Vendors_4.0.2.tgz HTTP/1.1
Host: get.symfony.com
User-Agent: Guzzle/5.3.1 curl/7.54.0 PHP/7.1.11

< HTTP/1.1 403 Forbidden
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Connection: keep-alive
< Date: Fri, 22 Dec 2017 07:54:36 GMT
< Server: AmazonS3
< X-Cache: Error from cloudfront
< Via: 1.1 622b39b22357e70fa8da7e1f171019f3.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: 0V6zbKD1HZr--jUeArnd-YmhwR5dEkRxjuyslSJs6cLMQyhy90xC3A==
<
* Connection #1 to host get.symfony.com left intact



  [RuntimeException]
  The selected version (4.0.2) cannot be installed because it does not exist.
  Execute the following command to install the latest stable Symfony release:
  symfony.phar new just-testing



Exception trace:
 () at phar:///symfony.phar/src/Symfony/Installer/DownloadCommand.php:188
 Symfony\Installer\DownloadCommand->download() at phar:///symfony.phar/src/Symfony/Installer/NewCommand.php:67
 Symfony\Installer\NewCommand->execute() at phar:///symfony.phar/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///symfony.phar/vendor/symfony/console/Application.php:878
 Symfony\Component\Console\Application->doRunCommand() at phar:///symfony.phar/vendor/symfony/console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///symfony.phar/src/Symfony/Installer/Application.php:32
 Symfony\Installer\Application->doRun() at phar:///symfony.phar/vendor/symfony/console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///symfony.phar/symfony:46
 require() at /symfony.phar:10
```

**Comment by Pierstoval** [comment] 2017-12-23 11:41
@kniziol you should re-read the [Installing & setting up](http://symfony.com/doc/current/setup.html) on Symfony documentation, or re-read the [Download](http://symfony.com/download) page


![image](https://user-images.githubusercontent.com/3369266/34319301-87aada84-e7de-11e7-8d00-575a724dc924.png)
