### ISSUE TITLE
Installer *may* download as a corrupted file in Windows

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-installer#137] opened 2015-04-03 15:03 UTC
Hi guys!

In a training this week, a windows user got a corrupted `symfony` after running:

```
php -r "readfile('http://symfony.com/installer');" > symfony
```

When you run this, it just dumps out crazy binary code to the terminal. The file sorta looks how it should (if you look inside), but not exactly. It's also about twice the size. Here's the corrupted version: https://www.dropbox.com/s/pqks3797mxvcp2h/symfony-installer-corrupted?dl=0

Unfortunately, I can't repeat this, so it's bit of a shot in the dark. But in case someone can spot the potential issue *or* if someone else is having the issue, I wanted to post.

Cheers!

**Comment by javiereguiluz** [comment] 2015-04-03 15:22
Thanks for reporting this issue and for providing the corrupted file. I still don't understand the cause of the error, but I'll keep analyzing the file to see if I can find anything. Thanks.

**Comment by WouterJ** [comment] 2015-04-03 15:33
I've executed the command a couple times in a couple different locations on my windows PC, but I'm also unable to reproduce it.

However, I slowly start to think that we have to offer something else (e.g. global composer installation) than a phar. At least for Windows users, it'll be a much better experience:

* The command is installed globally without too much trouble. With the phar, it requires quite a few steps.
* The installation requires PHP to be available on the command line. this is not the default when installing Wamp/Xampp (Composer's Windows installer takes care of it, but the phar doesn't require to install Composer)
* The download/installation process relies on a very solid base (composer).

Btw, the file on dropbox is a complete binary file as far as I can tell. My working downloads have lots of plain text in them (including the file header). So I'm not sure what you mean with "The file sorta looks how it should" (but might be an encoding issue).

**Comment by javiereguiluz** [comment] 2015-04-03 15:42
@WouterJ when I open the corrupted file in a text editor I see the following, which is the same as the correct installer:

![corrupted_file](https://cloud.githubusercontent.com/assets/73419/6984322/eb602b78-da27-11e4-933e-fe095e3f6634.png)

Regarding the use of Composer, I'm afraid that I disagree completely. One of the advantages of the Symfony installer is precisely that you don't require to use Composer at all. Trust me because I have a lot of "horror stories" of people failing to install Composer (and Symfony via Composer) during workshops (by the way these errors mostly occur on Windows). If this new installer works properly, all these problems will disappear forever.

**Comment by weaverryan** [comment] 2015-04-03 15:50
Just for reference, when I open them with vim, here's the difference.

The corrupted file:

![screen shot 2015-04-03 at 11 46 02 am](https://cloud.githubusercontent.com/assets/121003/6984451/0d7b54e8-d9f7-11e4-8fc3-acd34061892d.png)

The working file:

![screen shot 2015-04-03 at 11 46 03 am](https://cloud.githubusercontent.com/assets/121003/6984461/2075a058-d9f7-11e4-97d9-0cd765f53fea.png)

And I agree with Javier, mostly because I think we *can* get this to work. The proof is that installing composer ultimately results in downloading a phar file. The Symfony installer is trying to do the same. So, in theory, getting the Symfony installer can/should be as fool-proof and reliable as downloading Composer. One difference with Composer is that the script you `fopen` is piped into PHP, and *that* script downloads the phar file. I don't know if we will need to follow that approach or not - if this were literally the only pending issue and nobody could repeat, it would be overkill. But if we do have some more problems, we can "take it up" to that level and follow Composer's lead.

**Comment by WouterJ** [comment] 2015-04-03 16:06
Let's first talk about the issue:

When opening the file in phpstorm, I get the same result as you:
![sf-installer-phpstorm](https://cloud.githubusercontent.com/assets/749025/6984578/9a8f1274-da2a-11e4-80e7-d44744a1f0e5.png)

When opening it in Vim, I get this:
![sf-installer-vim](https://cloud.githubusercontent.com/assets/749025/6984590/bc47698e-da2a-11e4-8f64-9f3f8c624a0b.png)

Now, if you look at the vim screenshot closely, you'll see that every character is in there, but with an extra `^@` symbol.

Searching a bit on this difference, I came across [this superuser question](http://superuser.com/a/75146):

 > I don't think your files are corrupted. Your example line looks like it contains regular text with null bytes between each character. This suggests it's a text file that's been encoded in UTF-16 but the byte-order mark is missing from the start of the file. See http://en.wikipedia.org/wiki/Byte-order%5Fmark

 > Suppose I open Notepad, type the word 'filename', and save as Unicode Big-endian. A hex dump of this file looks like this:

 >     fe ff 00 66 00 69 00 6c 00 65 00 6e 00 61 00 6d 00 65
 > If I open this file in Vim it looks fine - the 'fe ff' bytes tell Vim how the file is encoded. Now suppose I create a file containing the exact same sequence of bytes, but without the leading 'fe ff'. Vim inserts ^@ (or `<00>`, depending on your config), in place of the null bytes; Notepad inserts spaces.

Could this be related to this issue? (e.g., for some reason, the first bytes were not downloaded?)

---

About using Composer:

* @javiereguiluz, I don't have as much experience with beginners as you. So I trust you that it might be hard to install Composer. However, please note that downloading the phar for Windows will advertise downloading the tool localy, as making it global requires quite a few steps (find a dir that's in the PATH or create a new one and add it to the PATH; moving the phar to that directory; create a bat file that executes the phar in that directory; restart cmd).
* @weaverryan, there is a big difference between Composer's windows installation instructions and those of the symfony installer. For Composer, Windows users download an exe file that'll take care of the installation (making sure the correct things are in the PATH etc). See https://github.com/composer/windows-setup. For the installer, it's just downloading some file and executing it locally.

**Comment by weaverryan** [comment] 2015-04-03 16:20
@WouterJ 

1) First about the issue. Wow! Nice find! The filesize of the corrupted one *does* report as about twice the size of the correct one. The does seem a bit consistent with what we're seeing: 1 extra null byte added for every real character. So I definitely think it's some sort of file encoding error, but I don't know too much about this stuff. 

I used an `enca` tool locally, to get the encoding, and got this out:

A) enca -L none ~/Downloads/symfony.corrupted
```
Universal character set 2 bytes; UCS-2; BMP
  CRLF line terminators
  Byte order reversed in pairs (1,2 -> 2,1)
```

B) enca -L none ~/Downloads/symfony.working
```
Unrecognized encoding
```

I'm guessing the "Unrecognized encoding" in the working one is just because it's fully binary.

2) About Composer, it might be a cool idea to have an exe version like that for Symfony (if it's pretty straightforward). But the `readfile` option *also* works for Windows users. For this person in particular, he was able to use `readfile` to download Composer, but he was *not* able to use `readfile` to download the installer.

And I *did* add a "global installer" to Composer, which also "works" in Windows (well, works for me, but there are always edge cases!): https://github.com/composer/composer/pull/3130. But this stalled. Anyways, I don't want to get off course in case we don't need this, but this is another *possible* option.

**Comment by stof** [comment] 2015-04-03 16:23
@weaverryan the composer installer script is a text file (it is a PHP file), not a binary file (it does not download the phar directly with readline).

**Comment by weaverryan** [comment] 2015-04-03 16:27
@stof You're right. But what I mean is that this command worked for him:

```
php -r "readfile('https://getcomposer.org/installer');" | php
```

The `installer` is the PHP file you're talking about, so you're right. But what's interesting is that this installer `script` wasn't corrupted (i.e. it piped into php just fine and did its work of downloading the actual phar). But, the `readfile` for the Symfony installer:

```
php -r "readfile('http://symfony.com/installer');" > symfony
```

DID result in a corrupted file. When you `php symfony` this, things went bananas :).

**Comment by weaverryan** [comment] 2015-04-03 16:29
And I can think of at least 2 differences:

1) Symfony's URL redirects to the actual download page (I couldn't find anyone talking about this being a problem anywhere though)
2) Symfony's comes back with the `application/octet-stream` content-type header, whereas Composer literally uses `text/plain`.

**Comment by WouterJ** [comment] 2015-04-03 17:06
@weaverryan the difference is that with `readfile('https://getcomposer.org/installer')`, PHP has to download a plain text file (just plain PHP), whereas with `readfile('https://symfony.com/installer')`, PHP has to download a binary file.

That this problem has occured on Windows is consistent with this, as Windows has differences between reading binary and text files:

 > **Windows offers a text-mode translation flag ('t')** which will transparently translate \n to \r\n when working with the file. In contrast, **you can also use 'b' to force binary mode**, which will not translate your data. To use these flags, specify either 'b' or 't' as the last character of the mode parameter.

 > **The default translation mode depends on the SAPI and version of PHP that you are using, so you are encouraged to always specify the appropriate flag for portability reasons.** You should use the 't' mode if you are working with plain-text files and you use \n to delimit your line endings in your script, but expect your files to be readable with applications such as notepad. You should use the 'b' in all other cases.

 > **If you do not specify the 'b' flag when working with binary files, you may experience strange problems with your data, including broken image files** and strange problems with \r\n characters.
 > -- http://php.net/manual/en/function.fopen.php

**Comment by sr972** [comment] 2015-04-03 18:29
Hi,

if it's really related to UTF-16 or -32 and a missing BOM coming up, i've got the question if you can remember what default language your student had on his system or additional languages? Something like cyrilic?

Probably some headers are not set correct or missing, when grabbing the file?

**Comment by Pierstoval** [comment] 2015-04-03 18:29
It seems that php's `readfile` function forces the addition of a BOM.
 
We might need to propose an intermediate text file similar to Composer's one in order to download the Symfony installer. Then, with this installer, we might do something like this:
`php -r "readfile('http://symfony.com/installer');" | php`
And the `http://symfony.com/installer` file would only contain something like this:

```php
$curl = curl_init("http://symfony.com/symfony.phar");
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl, CURLOPT_BINARYTRANSFER, true);
$binary = curl_exec($curl);
file_put_contents('symfony', $binary);
``` 

With Curl, we ensure that the returned file is a binary file and no other treatment is made over the content.
 
Does it sound like a good idea? :confused:

**Comment by WouterJ** [comment] 2015-04-03 21:09
@Pierstoval wouldn't this mean we require on CURL again? As that's not something we should want, as the `readfile` alternative is exactly to avoid the CURL dependency (it isn't enabled/available in Windows by default IIRC).

**Comment by weaverryan** [comment] 2015-04-08 18:12
@WouterJ But the basic point from @Pierstoval is still valid - Composer actually has quite a large installer file for accomplishing this (I think a lot of the size is due to ssl, but that would also be a good idea): https://getcomposer.org/installer. But it also seems pretty stable - no new commits since Oct: https://github.com/composer/getcomposer.org/blob/master/web/installer

**Comment by johnstevenson** [comment] 2015-04-30 09:02
@weaverryan 
>Btw, the Composer guys use a combination of stream_context_create and file_get_contents to download the file in their installer. However, keep in mind that their installer is only targetted for Unix, as Windows has a dedicated installer.

FYI the installer is targeted for both platforms. In fact the Windows exe installer runs php to download the install script (https://getcomposer.org/installer), via `stream_context_create` and `copy`. This is then executed with a simple `include`.

**Comment by mediamonks-robert** [comment] 2015-06-16 18:34
I wouldn't work for me when running the download command with PowerShell (I got the garbage ouput as stated by some else), when I run the command with cmd.exe it works fine so I guess it has something to do with PowerShell, not Windows in general.

**Comment by WouterJ** [comment] 2015-06-17 11:47
I can confirm that this happens when using Powershell.

**Comment by javiereguiluz** [comment] 2015-06-17 12:49
@mediamonks-robert and @WouterJ thanks for identifying the root cause of this error. Sadly, I can't work on fixing it because I have no access to Windows machines. However, I'd be glad to review any pull request submitted to fix this error. Thanks.

**Comment by futurevision** [comment] 2015-06-17 13:20
PR #169 updates the README.md with a new install command which should work with both cmd and PowerShell :)

**Comment by WouterJ** [comment] 2015-06-17 13:57
Btw, the problem is explained in [this SO answer](http://stackoverflow.com/a/11148692/1149495):

 > In PowerShell `>` is effectively the same as `| Out-File` and Out-File defaults to Unicode encoding. Try this instead of using `>`:

 >     ... | Out-File outputfile -encoding ASCII

**Comment by futurevision** [comment] 2015-06-17 13:59
I found that solution too but that doesn't work with cmd.exe so it would be best to have 1 install command that just works instead of having 2 :)

**Comment by weaverryan** [comment] 2015-06-17 16:11
@javiereguiluz FYI - you can virtualize windows for free: http://dev.modern.ie/tools/vms/

**Comment by rafaelmb** [comment] 2015-07-07 18:15
I have this same error trying to download the symfony installer using powershell and cmd. It's still reproductible in my machine so if there's anything I can give to help I will be glad.
The only way I've managed to download it was using the "git shell" which I believe is Cygwin

**Comment by javiereguiluz** [comment] 2015-07-07 20:28
@rafaelmb there is a proposed solution to fix this issue and we need people to test it. So, if possible, please try to download the installer as follows. Thanks!

```bash
c:\> php -r "file_put_contents('symfony', file_get_contents('http://symfony.com/installer'));"
```

**Comment by rafaelmb** [comment] 2015-07-08 12:20
@javiereguiluz I can confirm that this works for power shell and cmd. Thanks!

**Comment by javiereguiluz** [comment] 2015-09-10 13:06
Closing it as fixed thanks to the new `file_put_contents(...)` recommendation. Thank you all for your help reporting, debugging and providing a solution for this issue.

**Closed by javiereguiluz** 2015-09-10 13:06 UTC
Labels: bug
