### ISSUE TITLE
Installer requires Intl

### ISSUE THREAD

**Issue by unkind** [symfony/symfony-installer#163] opened 2015-05-25 22:13 UTC
```
$ php symfony.phar new foo

 Downloading Symfony...

    4.92 MB/4.92 MB ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100%

 Preparing project...

  [Symfony\Component\Intl\Exception\MethodArgumentValueNotImplementedException]
  The Symfony\Component\Intl\Collator\Collator::__construct() method's argument $locale
  value 'fr_FR' behavior is not implemented. Only the locale "en" is supported.  Please install
  the "intl" extension for full localization capabilities.

new directory [version]
```
http://symfony.com/doc/current/reference/requirements.html — this page states that Symfony has optional dependency on Intl, why does installer require it?

Symfony Installer has version 1.1.3.

**Comment by unkind** [comment] 2015-05-25 22:40
Well, it looks like BC break in either symfony-standard or symfony/symfony. I'm sure there was no such requirement in the past. Where I should create an issue?

**Comment by fabpot** [comment] 2015-05-30 18:46
This one is critical. Anyone having a look at it?

**Comment by javiereguiluz** [comment] 2015-05-30 18:54
I can't reproduce this error with the same isntaller version you are using:

![symfony_installer](https://cloud.githubusercontent.com/assets/73419/7898859/f4fdb7be-070d-11e5-8450-b41c3a97f228.png)

Could you please share more details about the error? Which operating system are you using? Which PHP version? Are you using a virtual machine? Thanks.

**Comment by fabpot** [comment] 2015-05-30 18:59
@javiereguiluz You just have intl installed and enabled, but we don't.

**Comment by javiereguiluz** [comment] 2015-05-30 19:06
I've disabled `intl` extension and the problem seems to be related with this code of the `SymfonyRequirements.php` file:

```php
        if (class_exists('Collator')) {
            $this->addRecommendation(
                null !== new Collator('fr_FR'),
                'intl extension should be correctly configured',
                'The intl extension does not behave properly. This problem is typical on PHP 5.3.X x64 WIN builds.'
            );
        }
```

Full error trace:

```
Exception trace:
 () at /Users/javier/Desktop/test_without_intl/vendor/symfony/symfony/src/Symfony/Component/Intl/Collator/Collator.php:80
 Symfony\Component\Intl\Collator\Collator->__construct() at /Users/javier/Desktop/test_without_intl/app/SymfonyRequirements.php:648
 SymfonyRequirements->__construct() at phar:///usr/local/bin/symfony/src/Symfony/Installer/DownloadCommand.php:237
 Symfony\Installer\DownloadCommand->checkSymfonyRequirements() at phar:///usr/local/bin/symfony/src/Symfony/Installer/NewCommand.php:65
 Symfony\Installer\NewCommand->execute() at phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/symfony/symfony:35
 require() at /usr/local/bin/symfony:10
```

**Comment by javiereguiluz** [comment] 2015-05-30 19:18
@stof in case SymfonyRequirements is the actual error, do you think it's better to fix it upstream in https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Resources/skeleton/app/SymfonyRequirements.php#L646 or should we "hack" the installer somehow? Thanks.

**Comment by weaverryan** [comment] 2015-05-30 22:01
It seems like this bug has been around for awhile - probably introduced with the `Intl` refactoring in Symfony 2.6 (I can find people complaining about this error at least back to Jan 2015). The whole `Collator` thing originated in sensiolabs/SensioDistributionBundle#59

We should definitely fix it up-stream: 

A) Fix it in SensioDistributionBundle
B) Update the composer.lock file in the SE to get the latest DistroBundle with the fix
C) Wait for a patch release

In `DownloadCommand`, we could temporarily wrap the `new SymfonyRequirements()` with a try-catch for the exception. If we did that, we could not tell them if they have any errors, but we could continue their installation. So, not too sure about this one.

**Comment by weaverryan** [comment] 2015-05-30 22:28
Introduced a fix for the SensioDistributionBundle at sensio/SensioDistributionBundle#207.

@javiereguiluz can you test that?

**Comment by javiereguiluz** [comment] 2015-05-31 08:19
@weaverryan thanks for working on this. Here it is the result of the test:

### Before

![before](https://cloud.githubusercontent.com/assets/73419/7901245/28f98604-077e-11e5-9ebd-dfdfc252df68.png)

### The patch

To test the patch you provided for SensioDistributionBundle, I added the following in the `checkSymfonyRequirements()` method:

```php
protected function checkSymfonyRequirements()
{
    $originalRequirements = file_get_contents($this->projectDir.'/app/SymfonyRequirements.php');
    $newRequirements = str_replace(
        "if (class_exists('Collator')) {",
        "if (class_exists('Collator') && extension_loaded('intl')) {",
        $originalRequirements
    );
    file_put_contents($this->projectDir.'/app/SymfonyRequirements.php', $newRequirements);

    // ...
}
```

### The result

The original error has gone, but now I get the following:

![after](https://cloud.githubusercontent.com/assets/73419/7901252/72fd5b4a-077e-11e5-9780-fe425806118f.png)

**Comment by weaverryan** [comment] 2015-05-31 15:02
Thanks Javier! Can you try it again now? You can probably also test this by downloading my new `SymfonyRequirements.php`, just putting that into a project (post using the installer), and then running `php check.php`. But try that first to make sure you get the error :).

**Comment by javiereguiluz** [comment] 2015-05-31 16:42
@weaverryan I can confirm that after applying your last patch, the error is gone (and the `app/check.php` fiel works too):

![installer_works_without_intl](https://cloud.githubusercontent.com/assets/73419/7902767/bfcdb870-07c4-11e5-85a9-1b056c27d1c3.png)

**Comment by weaverryan** [comment] 2015-05-31 17:55
excellent - thanks!

**Comment by fabpot** [comment] 2015-06-01 01:48
Fixed now in the bundle.

**Comment by ivansf** [comment] 2015-06-01 17:37
how do I get this update?

$ symfony self-update
Symfony Installer is already up to date.

**Comment by unkind** [comment] 2015-06-01 17:46
We should wait for release of symfony/symfony-standard.

**Comment by xabbuh** [comment] 2015-06-04 07:31
@fabpot This will only be included in the next builds of the Framework Standard Edition, right? So, don't we still have to find a solution for the installer for all older versions?

**Comment by xabbuh** [comment] 2015-06-06 10:22
@javiereguiluz @fabpot ping

**Comment by tomlankhorst** [comment] 2015-06-07 13:41
Trying to simply start a new project. Before I've done any coding at all I already encounter this error...

**Comment by thasly** [comment] 2015-06-08 16:07
Same for me... 
tried to install the intl using the composer with no luck

any idea when the installer will be updated?

**Comment by javiereguiluz** [comment] 2015-06-08 16:10
@weaverryan @xabbuh @stof what can we do from the installer point of view to avoid this issue? Should we wrap the requirements checker in a `try ... catch` block to fail silently?

**Comment by tomlankhorst** [comment] 2015-06-08 16:13
Just check the requirements before trying to create a new project? Maybe
add 'symfony check' to explicitly call the requirements check and use it in
the 'new' method to check for missing reqs.


Tom Lankhorst

​
<http://webhub.nl/>
m. +31 (0)6 307 41 869
e. info@tomlankhorst.nl  Meeuwenstraat 54
7523 XV Enschede


2015-06-08 18:10 GMT+02:00 Javier Eguiluz <notifications@github.com>:

**Comment by xabbuh** [comment] 2015-06-09 21:10
see #166

**Closed** 2015-06-10 06:35 UTC
Labels: bug
