### ISSUE TITLE
.gitignore file isn't downloaded when using the installer

### ISSUE THREAD

**Issue by CDOLago** [symfony/symfony-installer#249] opened 2016-04-30 12:54 UTC
Using fresh Windows 10 64 bits installation.
Installed Laragon: https://laragon.org/
Opened terminal and executed command: `php symfony.phar new projectName lts `
Didn't throw any errors.

.gitignore file ins't included in the project root.

**Comment by xabbuh** [comment] 2016-04-30 13:03
Does this change when you choose a version explicitly (like `2.8`)?

**Comment by CDOLago** [comment] 2016-04-30 18:22
I've tried the following commands and the same thing happens:

`php symfony.phar new projectName`
`php symfony.phar new projectName 2.8`

With an older version of symfony.phar it has no problems so it definitely has something do to with that recent commit.

**Comment by javiereguiluz** [comment] 2016-05-08 17:30
I can't reproduce this with a Mac OS. The `.gitignore` is included in the project root and with the right contents. Let's wait for a Windows user to confirm this. Thanks.

**Comment by xabbuh** [comment] 2016-05-08 20:34
@WouterJ or @Iltar: Are you able to reproduce the issue?

**Comment by iltar** [comment] 2016-05-08 20:51
I don't have a .gitignore either (w10 64bit). I'm using git bash though;

```
$ curl -LsS https://symfony.com/installer -o symfony
$ chmod a+x symfony
$ php symfony new projectName lts
```

```
 Preparing project...

 OK  Symfony 2.8.5 was successfully installed. Now you can:

    * Change your current directory to C:\Users\Iltar\projects\test\projectName

    * Configure your application in app/config/parameters.yml file.

    * Run your application:
        1. Execute the php app/console server:run command.
        2. Browse to the http://localhost:8000 URL.

    * Read the documentation at http://symfony.com/doc

```
```
Iltar@ANYONE /C/Users/Iltar/projects/test/projectName
$ ll -a
total 49
drwxr-xr-x    1 Iltar    Administ     4096 May  8 22:46 .
drwxr-xr-x    1 Iltar    Administ        0 May  8 22:46 ..
-rw-r--r--    1 Iltar    Administ       77 May  8 22:46 README.md
drwxr-xr-x    1 Iltar    Administ     4096 May  8 22:46 app
drwxr-xr-x    1 Iltar    Administ        0 May  8 22:46 bin
-rw-r--r--    1 Iltar    Administ     2244 May  8 22:46 composer.json
-rw-r--r--    1 Iltar    Administ    78013 May  8 22:46 composer.lock
drwxr-xr-x    1 Iltar    Administ        0 May  8 22:46 src
drwxr-xr-x    1 Iltar    Administ     4096 May  8 22:46 vendor
drwxr-xr-x    1 Iltar    Administ     4096 May  8 22:46 web
```

**Comment by WouterJ** [comment] 2016-05-08 21:05
I can reproduce this with anything (it applies to some logic in Symfony, not just to a specific version). When dumping the surpressed exception, I get:

 > cURL error 60: SSL certificate problem: unable to get local issuer certificate

**Comment by iltar** [comment] 2016-05-09 06:16
I've just ran it on Ubuntu, same commands as above:

```
$ ll -a
total 120K
drwxr-xr-x  7 ivanderberg hostteam 4,0K May  9 08:14 .
drwxrwxr-x  3 ivanderberg hostteam 4,0K May  9 08:14 ..
drwxr-xr-x  6 ivanderberg hostteam 4,0K May  9 08:14 app
drwxr-xr-x  2 ivanderberg hostteam 4,0K May  9 08:14 bin
-rw-r--r--  1 ivanderberg hostteam 2,2K May  9 08:14 composer.json
-rw-r--r--  1 ivanderberg hostteam  77K May  9 08:14 composer.lock
-rw-rw-rw-  1 ivanderberg hostteam  185 May  9 08:14 .gitignore
-rw-rw-rw-  1 ivanderberg hostteam   76 May  9 08:14 README.md
drwxr-xr-x  3 ivanderberg hostteam 4,0K May  9 08:14 src
drwxr-xr-x 15 ivanderberg hostteam 4,0K May  9 08:14 vendor
drwxr-xr-x  3 ivanderberg hostteam 4,0K May  3 07:47 web
```

*While the actual symfony command took 1~2 minutes for me on windows, it was a matter of seconds on linux*

**Comment by Pierstoval** [comment] 2016-06-02 15:21
Got the same problem on my Windows machine: symfony is installed but the `.gitignore` file is not created. Some students of mine report the same issue on windows 10.

Here's the full output:

```

Pierstoval@Pierstoval MINGW64 /www
$ symfony --version
Symfony Installer version 1.5.1

Pierstoval@Pierstoval MINGW64 /www
$ symfony new sftest -vvv

 Downloading Symfony...

*   Trying 54.247.104.40...
* Connected to symfony.com (54.247.104.40) port 80 (#0)
> GET /download?v=Symfony_Standard_Vendors_latest.tgz HTTP/1.1
Host: symfony.com
User-Agent: Guzzle/5.3.0 curl/7.47.1 PHP/5.6.22

< HTTP/1.1 302 Found
< Age: 278
< Cache-Control: public, s-maxage=600
< Content-Type: text/html; charset=UTF-8
< Date: Thu, 02 Jun 2016 15:14:08 GMT
< Location: http://get.symfony.com/Symfony_Standard_Vendors_3.1.0.tgz
< Server: nginx/1.4.6 (Ubuntu)
< Via: 1.1 varnish-v4
< X-Varnish: 584554226 588547242
< Content-Length: 4399
< Connection: keep-alive
<
* Connection #0 to host symfony.com left intact
    5.09 MB/5.09 MB ============================================================  100%*   Trying 54.239.158.151...
* Connected to get.symfony.com (54.239.158.151) port 80 (#1)
> GET /Symfony_Standard_Vendors_3.1.0.tgz HTTP/1.1
Host: get.symfony.com
User-Agent: Guzzle/5.3.0 curl/7.47.1 PHP/5.6.22

< HTTP/1.1 200 OK
< Content-Type: application/x-tar
< Content-Length: 5339493
< Connection: keep-alive
< Date: Mon, 30 May 2016 08:12:06 GMT
< x-amz-meta-s3cmd-attrs: uid:501/gname:staff/uname:fabien/gid:20/mode:33188/mtime:1464594693/atime:1464594804/md5:8e11b980df2ea4717b6dd7c5dd991c48/ctime:1464594693
< Last-Modified: Mon, 30 May 2016 07:54:56 GMT
< ETag: "8e11b980df2ea4717b6dd7c5dd991c48"
< Accept-Ranges: bytes
< Server: AmazonS3
< Age: 22297
< X-Cache: Hit from cloudfront
< Via: 1.1 fffec0bd5fe752e118ffb0f18477eedd.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: 5m8CV-emTRFLHOeKmgb9Jap5lJurd3o6krDsSV1J4xU3D5MYzhN6XQ==
<
* Connection #1 to host get.symfony.com left intact


 Preparing project...

 OK  Symfony 3.1.0 was successfully installed. Now you can:

    * Change your current directory to D:\www\sftest

    * Configure your application in app/config/parameters.yml file.

    * Run your application:
        1. Execute the php bin/console server:run command.
        2. Browse to the http://localhost:8000 URL.

    * Read the documentation at http://symfony.com/doc

*   Trying 185.31.18.133...
* Connected to raw.githubusercontent.com (185.31.18.133) port 443 (#0)
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0

Pierstoval@Pierstoval MINGW64 /www
$ l sftest/
total 101K
drwxr-xr-x 1 Pierstoval 197121    0 juin   2 17:19 ./
drwxr-xr-x 1 Pierstoval 197121    0 juin   2 17:19 ../
drwxr-xr-x 1 Pierstoval 197121    0 juin   2 17:19 app/
drwxr-xr-x 1 Pierstoval 197121    0 juin   2 17:19 bin/
drwxr-xr-x 1 Pierstoval 197121    0 juin   2 17:19 src/
drwxr-xr-x 1 Pierstoval 197121    0 juin   2 17:19 tests/
drwxr-xr-x 1 Pierstoval 197121    0 juin   2 17:19 var/
drwxr-xr-x 1 Pierstoval 197121    0 juin   2 17:19 vendor/
drwxr-xr-x 1 Pierstoval 197121    0 juin   2 17:19 web/
-rw-r--r-- 1 Pierstoval 197121 2,5K juin   2 17:19 composer.json
-rw-r--r-- 1 Pierstoval 197121  73K juin   2 17:19 composer.lock
-rw-r--r-- 1 Pierstoval 197121  978 juin   2 17:18 phpunit.xml.dist
-rw-r--r-- 1 Pierstoval 197121   67 juin   2 17:19 README.md

```

**Comment by javiereguiluz** [comment] 2016-06-20 08:23
So far the best shot at finding the cause of this was provided by @WouterJ:

```
cURL error 60: SSL certificate problem: unable to get local issuer certificate
```

Given that this feature works on macOS and Linux, I guess the problem must be "Windows OS" or "PHP on Windows". Could this be solved by using https://github.com/composer/ca-bundle ?

**Comment by WouterJ** [comment] 2016-06-20 09:21
Using Composer CaBundle, I get:

 > cURL error 58: unable to set private key file: '...' type PEM

Which is probably due to a malformed default pem file in the Composer CaBundle (however, this is just based on Google, as I don't know anything about this stuff).

**Comment by antoniogarcia78** [comment] 2016-06-24 07:26
if fix the "cURL error 60" using the solution of @javiereguiluz in issue #237 
I have Windows 10 64bits , Xampp with PHP 5.6
For me the problem appear after update the symfony instaler

**Comment by javiereguiluz** [comment] 2016-07-14 09:46
I'm closing this in favor of the more generic #268 issue.

**Closed by javiereguiluz** 2016-07-14 09:46 UTC
Labels: bug

**Comment by AmaliDeveloper** [comment] 2017-03-13 00:32
Hey you can get the solution in this tutorial Good Work [Link](https://youtu.be/gh1T8wS2alM)
