### ISSUE TITLE
Add a option for list supported Symfony versions

### ISSUE THREAD

**Issue by paquitodev** [symfony/symfony-installer#202] opened 2015-11-23 13:54 UTC
Will be nice if an option for show us which versions with possible command line example for each can be installed through this tool, right now I am complete loose around install Symfony 2.8 or 3.0 and has not a clue, could this be added as a feature for next releases?

**Comment by Pierstoval** [comment] 2015-11-23 13:58
I proposed it some time ago and it was refused by @fabpot IIRC, but if you need this you can still use the versions file : https://symfony.com/versions.json

**Comment by paquitodev** [comment] 2015-11-23 14:01
@Pierstoval ok I see the .json file but I am not sure at all which command line I should use for install 2.8, is the one below?

    symfony new my_project 2.8.0-BETA1

**Comment by Pierstoval** [comment] 2015-11-23 14:06
Exactly :)

**Comment by paquitodev** [comment] 2015-11-23 14:07
Thx for your help @Pierstoval

**Comment by paquitodev** [comment] 2015-11-23 14:19
@Pierstoval I need your help with something else here, take a look to the following commands and its output:

	symfony_installer new platform-cm 2.8.0-beta1

	  WARNING  You are downloading an unstable Symfony version.

	 Downloading Symfony...

		5.23 MB/5.23 MB ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100%

	 Preparing project...

	 ✕  Symfony 2.8.x-dev was successfully installed but your system doesn't meet its
		 technical requirements! Fix the following issues before executing
		 your Symfony application:

	 * date.timezone setting must be set
	   > Set the "date.timezone" setting in php.ini* (like Europe/Paris).

	 After fixing these issues, re-check Symfony requirements executing this command:

	   php platform-cm/app/check.php

	 Then, you can:

		* Change your current directory to /var/www/html/platform-cm


		* Configure your application in app/config/parameters.yml file.

		* Run your application:
			1. Execute the php app/console server:run command.
			2. Browse to the http://localhost:8000 URL.

		* Read the documentation at http://symfony.com/doc

I did fixed the issue with `date.timezone` but then:

	# composer update
	Loading composer repositories with package information
	Updating dependencies (including require-dev)
	  - Removing symfony/security-acl (v2.7.6)
	  - Installing symfony/security-acl (v2.7.7)
		Downloading: 100%

	  - Removing doctrine/orm (v2.5.1)
	  - Installing doctrine/orm (v2.5.2)
		Downloading: 100%

	  - Removing symfony/monolog-bundle (2.8.1)
	  - Installing symfony/monolog-bundle (v2.8.2)
		Downloading: 100%

	  - Removing symfony/phpunit-bridge (v2.7.6)
	  - Installing symfony/phpunit-bridge (v2.7.7)
		Downloading: 100%

	  - Updating symfony/symfony 2.8.x-dev (3b99b3a => 2dbb75a)



	  [RuntimeException]
	  The .git directory is missing from /var/www/html/platform-cm/vendor/symfony/symfony, see https://getcomposer.org/commit-deps for more information

Ups, error while run `composer update` how this can be fixed?

**Comment by stof** [comment] 2015-11-23 14:35
this seems like a bug in the zip archive created by the symfony server.

@javiereguiluz please make sure that ``.git`` folder are not removed from vendors when generating the archives, or that they are never here in the first place (i.e. none of the packages is installed from source)

**Comment by Pierstoval** [comment] 2015-11-23 14:39
The problem is that `.git` directories mean that some dependencies are not required with a "released" version. A `.git` directory is heavy and brings nothing in the first place of a composer-dependent app.
IMO the problem does not come from the zip archive generator, but more on the `composer.json` file of the project that requires dev versions.
 
Even if the framework is still in beta, it should not require `@dev` dependencies. `beta` are good because most of the time they are released, so findable with a tag, and therefore a zipball directly from github, contrary to `dev` which necessitates a `git clone` at first call.

**Comment by javiereguiluz** [comment] 2015-11-23 14:54
The [script we use to generate ZIP packages](https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Resources/bin/build.sh) is public. In [this line](https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Resources/bin/build.sh#L51) we delete the `.git` directory.

**Comment by stof** [comment] 2015-11-23 15:45
@javiereguiluz and this is precisely the bug: the composer metadata still contains the info it is installed from source, while it is not anymore

**Comment by stof** [comment] 2015-11-23 15:46
@Pierstoval dev versions *can* be installed from dist too (Github generates archives for any commit). But Composer will use the source install by default.

**Comment by Pierstoval** [comment] 2015-11-23 15:50
@stof I know dev versions can be installed from dist, but a git repository (or many if there are more `@dev` dependencies) sounds like a heavy cross in a zipball that serve as reference to download the standard edition :confused:.

**Comment by javiereguiluz** [comment] 2015-11-23 15:52
Should we change this line of the script:

```
composer create-project -n symfony/framework-standard-edition /tmp/Symfony $2
```

by this one?

```
composer create-project -n --prefer-dist symfony/framework-standard-edition /tmp/Symfony $2
```

**Comment by stof** [comment] 2015-11-23 16:11
@javiereguiluz it would be better yes

**Comment by paquitodev** [comment] 2015-11-27 14:47
@javiereguiluz @stof @Pierstoval (happy thanksgiving to all of yours) I did update the symfony installer, create a new project for test 2.8.0-BETA1 but I can't update composer dependencies, at least the ones related to Symfony itself, take a look to the output below:

    # symfony_installer self-update
    // updating Symfony Installer to 1.4.1 version
    # symfony_installer new sf28 2.8.0-BETA1

      WARNING  You are downloading an unstable Symfony version.

     Downloading Symfony...

        5.23 MB/5.23 MB ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100%

     Preparing project...
     ✔  Symfony 2.8.x-dev was successfully installed. Now you can:
        * Change your current directory to /var/www/html/sf28
        * Configure your application in app/config/parameters.yml file.
        * Run your application:
            1. Execute the php app/console server:run command.
            2. Browse to the http://localhost:8000 URL.
        * Read the documentation at http://symfony.com/doc

    # composer update
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
      - Removing symfony/security-acl (v2.7.6)
      - Installing symfony/security-acl (v2.7.7)
        Loading from cache

      - Removing doctrine/orm (v2.5.1)
      - Installing doctrine/orm (v2.5.2)
        Loading from cache

      - Removing symfony/monolog-bundle (2.8.1)
      - Installing symfony/monolog-bundle (v2.8.2)
        Loading from cache

      - Removing symfony/phpunit-bridge (v2.7.6)
      - Installing symfony/phpunit-bridge (v2.7.7)
        Loading from cache

      - Removing doctrine/doctrine-cache-bundle (1.2.1)
      - Installing doctrine/doctrine-cache-bundle (1.2.2)
        Downloading: 100%

      - Updating symfony/symfony 2.8.x-dev (3b99b3a => fad3d38)

      [RuntimeException]
      The .git directory is missing from /var/www/html/sf28/vendor/symfony/symfony, see https://getcomposer.org/commit-deps for more information

    update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--] [<packages>]...

Any advice?

**Comment by paquitodev** [comment] 2015-11-27 14:53
BTW, sorry for the little kidnapping, @Pierstoval did your PR being accepted? Can we start using Symfony 3.0 from within the installer? Is not at https://symfony.com/versions.json just yet but I see something in the latest commit from hours ago, any light?

**Comment by ogizanagi** [comment] 2015-11-27 15:25
@paquitodev : You can actually start using it, but you'll need to upgrade your symfony installer. 
However, for now, you'll have to build the phar yourself:
```bash
# Linux / Mac OS X
$ git clone git@github.com:symfony/symfony-installer.git
$ cd symfony-installer
$ box build -v
$ mv symfony.phar /usr/local/bin/symfony
$ symfony --version

Symfony Installer version 1.4.1

$ cd ../
$ symfony new sf3-app 3.0.0-BETA1
```

You'll certainly need to install [`box`](https://github.com/box-project/box2) for the above commands:
```bash 
$ curl -LSs http://box-project.github.io/box2/installer.php | php
$ sudo mv box.phar /usr/local/bin/box
$ sudo chmod a+x /usr/local/bin/box
```

**Comment by javiereguiluz** [comment] 2015-11-27 15:30
@paquitodev the answer provided by @ogizanagi is correct, but you probably don't need to do all that. Just execute `symfony self-update` to get the latest version of the installer.

**Comment by paquitodev** [comment] 2015-11-27 15:33
@ogizanagi I don't think I need to do that, just doing `symfony_installer self-update` will be enough in fact after run that command and as I show in previous post running:

    # symfony_installer --version
    Symfony Installer version 1.4.1

So, same result as you after compile ;)

**Comment by javiereguiluz** [comment] 2015-11-27 15:35
@paquitodev cool! Now get Symfony 3 as follows:

```
$ symfony new my_project 3.0.0-BETA1
```

**Comment by ogizanagi** [comment] 2015-11-27 15:36
@javiereguiluz @paquitodev:  Hmmm, I suggested to do that because the version I get by using `symfony selfupdate` or on `http://symfony.com/installer` was still `1.3.3` when I tried :sweat_smile:

**Comment by paquitodev** [comment] 2015-11-27 15:38
@ogizanagi no problem thanks for your suggestion is welcome, @javiereguiluz I am getting the same issue with Symfony 3.0 BETA1 as well, see below:

    # symfony_installer new sf3-app 3.0.0-BETA1

      WARNING  You are downloading an unstable Symfony version.

     Downloading Symfony...

        4.99 MB/4.99 MB ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100%

     Preparing project...

     ✔  Symfony dev-master was successfully installed. Now you can:
        * Change your current directory to /var/www/html/sf3-app
        * Configure your application in app/config/parameters.yml file.
        * Run your application:
            1. Execute the php bin/console server:run command.
            2. Browse to the http://localhost:8000 URL.
        * Read the documentation at http://symfony.com/doc

    [root@ws sf3-app]# composer update
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
      - Removing symfony/phpunit-bridge (v2.7.6)
      - Installing symfony/phpunit-bridge (v2.7.7)
        Loading from cache

      - Removing symfony/swiftmailer-bridge (v2.7.6)
      - Installing symfony/swiftmailer-bridge (v2.7.7)
        Downloading: 100%

      - Updating symfony/symfony dev-master (bd54cb4 => 743e670)

      [RuntimeException]
      The .git directory is missing from /var/www/html/sf3-app/vendor/symfony/symfony, see https://getcomposer.org/commit-deps for more information

    update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--] [<packages>]...

**Comment by javiereguiluz** [comment] 2015-11-27 15:39
@paquitodev yes, because the 3.0.0-BETA1 package didn't change since last time. It will be updated for the next version.

**Comment by paquitodev** [comment] 2015-11-27 15:42
@javiereguiluz so you mean I can't run composer update or I am not following you? What happen if I add some bundles and want to run `composer update` instead of `composer update bundle`?

**Comment by javiereguiluz** [comment] 2015-12-17 10:14
Closing it as fixed:

```
$ symfony new my_project

  ...
  ✔  Symfony 3.0.0 was successfully installed.
  ...

$ cd my_project
$ composer update

Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing doctrine/cache (v1.5.1)
  - Installing doctrine/cache (v1.5.2)
    Loading from cache

  - Removing doctrine/common (v2.5.1)
  - Installing doctrine/common (v2.5.2)
    Loading from cache

  - Removing paragonie/random_compat (1.1.0)
  - Installing paragonie/random_compat (1.1.4)
    Loading from cache

  - Removing doctrine/doctrine-bundle (1.6.0)
  - Installing doctrine/doctrine-bundle (1.6.1)
    Loading from cache

  - Removing sensio/generator-bundle (v3.0.0)
  - Installing sensio/generator-bundle (v3.0.1)
    Loading from cache

Writing lock file
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

 // Clearing the cache for the dev environment with debug true


 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.


> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets

 Trying to install assets as relative symbolic links.

 --- ----------------- ------------------
      Bundle            Method / Error
 --- ----------------- ------------------
  ✔   FrameworkBundle   relative symlink
 --- ----------------- ------------------


 [OK] All assets were successfully installed.


> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget
```

**Closed by javiereguiluz** 2015-12-17 10:14 UTC
