### ISSUE TITLE
Installation not possible in the existing directory that can not be removed.

### ISSUE THREAD

**Issue by gander** [symfony/symfony-installer#129] opened 2015-03-31 11:38 UTC
`~/bin/symfony-installer/symfony new ~/workspace/`

`Fatal error: Uncaught exception 'RuntimeException' with message 'Could not delete /home/codio/workspace: rmdir(/home/codio/workspace): Device or resource busy' in /home/codio/bin/symfony-installer/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php:177`

**Comment by Pierstoval** [comment] 2015-03-31 11:58
Have you tried to go to your home directory and try to execute `symfony new workspace` ?

**Comment by gander** [comment] 2015-03-31 12:14
`rm: cannot remove 'workspace': Device or resource busy`

This directory can not be removed. This is blocked by the system, and the intended effect. Why Symfony Installer must delete this folder?

**Comment by Pierstoval** [comment] 2015-03-31 12:20
Is the directory empty ?

**Comment by gander** [comment] 2015-03-31 12:40
>codio:~$ pwd 
>/home/codio 
>codio:~$ ls -al /home/codio/workspace/ 
>total 4 
>drwxr-xr-x  2 codio codio    6 Mar 31 12:10 . 
>drwxr-xr-x 24 codio codio 4096 Mar 31 12:08 .. 
>codio:~$ rm -fr /home/codio/workspace/ 
>rm: cannot remove `/home/codio/workspace': Device or resource busy 

But why you are focusing on the fact that I can not delete this folder? This is not a problem! Let's focus on that to improve the installer.

**Comment by Pierstoval** [comment] 2015-03-31 12:56
It's not normal that the installer tries to delete this directory :confused:

**Comment by gander** [comment] 2015-03-31 13:02
>codio:~$ ls -al workspace 
>total 4 
>drwxr-xr-x  2 codio codio    6 Mar 31 12:58 . 
>drwxr-xr-x 24 codio codio 4096 Mar 31 12:08 .. 
>codio:~$ symfony -vvv new workspace 
> 
> Downloading Symfony... 
> Preparing project... 
> 
>  [RuntimeException] 
>  Symfony can't be installed because the downloaded package is corrupted 
>  or because the installer doesn't have enough permissions to uncompress and 
>  rename the package contents. 
>  To solve this issue, check the permissions of the /home/codio directory and 
>  try executing this command again: 
>  symfony new workspace 
> 
>Exception trace: 
> () at phar:///home/codio/bin/symfony/src/Symfony/Installer/DownloadCommand.php:162 
> Symfony\Installer\DownloadCommand->extract() at phar:///home/codio/bin/symfony/src/Symfony/Installer/NewCommand.php:67 
> Symfony\Installer\NewCommand->execute() at phar:///home/codio/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252 
> Symfony\Component\Console\Command\Command->run() at phar:///home/codio/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:874 
> Symfony\Component\Console\Application->doRunCommand() at phar:///home/codio/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:195 
> Symfony\Component\Console\Application->doRun() at phar:///home/codio/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:126 
> Symfony\Component\Console\Application->run() at phar:///home/codio/bin/symfony/symfony:30 
> require() at /home/codio/bin/symfony:10 
> 
>new directory [version]

**Comment by Pierstoval** [comment] 2015-03-31 13:05
The error is now different than the previous one...

```shell
codio:~$ ls -al workspace 
total 4 
drwxr-xr-x 2 codio codio 6 Mar 31 12:58 . 
drwxr-xr-x 24 codio codio 4096 Mar 31 12:08 .. 
```
You seem not to have writing permissions on this directory

**Comment by gander** [comment] 2015-03-31 13:18
In this system, everything runs as `codio`:

>codio:~/workspace$ php -r '$here=realpath("."); var_dump($here, is_writable($here), is_readable($here));' 
>string(21) "/home/codio/workspace" 
>bool(true) 
>bool(true)

But let's assume it's a problem with permissions. I give `chmod 777` to `workspace`. The result is the same:

>codio:~$ ls -al workspace 
>total 4 
>drwxrwxrwx  2 codio codio    6 Mar 31 13:11 . 
>drwxr-xr-x 24 codio codio 4096 Mar 31 13:00 .. 
>codio:~$ symfony new workspace 
> 
> Downloading Symfony... 
> Preparing project... 
> 
>  [RuntimeException] 
>  Symfony can't be installed because the downloaded package is corrupted 
>  or because the installer doesn't have enough permissions to uncompress and 
>  rename the package contents. 
>  To solve this issue, check the permissions of the /home/codio directory and 
>  try executing this command again: 
>  symfony new workspace 
> 
>new directory [version]

**Comment by gander** [comment] 2015-03-31 13:51
>codio:~$ ~/bin/symfony-installer/symfony -vvv new ~/workspace/ 
> 
> Downloading Symfony... 
> Preparing project... 
> 
>Fatal error: Uncaught exception 'RuntimeException' with message 'Could not delete /home/codio/workspace: rmdir(/home/codio/workspace): Device or resource busy' in /home/codio/bin/symfony-installer/vendor/raulfraile/distill/src/Extracto
>r/Util/Filesystem.php:177 
>Stack trace: 
>#0 /home/codio/bin/symfony-installer/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php(113): Distill\Extractor\Util\Filesystem->rmdir('/home/codio/wor...') 
>#1 /home/codio/bin/symfony-installer/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php(87): Distill\Extractor\Util\Filesystem->removeDirectoryPhp('/home/codio/wor...') 
>#2 /home/codio/bin/symfony-installer/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php(33): Distill\Extractor\Util\Filesystem->removeDirectory('/home/codio/wor...') 
>#3 /home/codio/bin/symfony-installer/vendor/raulfraile/distill/src/Distill.php(206): Distill\Extractor\Util\Filesystem->remove('/home/codio/wor...') 
>#4 /home/codio/bin/symfony-installer/src/Symfony/Installer/DownloadCommand.php(166): Distill\Di in /home/codio/bin/symfony-installer/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php on line 177 
>
>codio:~$ stat ~/workspace/ 
>  File: `/home/codio/workspace/' 
>  Size: 22              Blocks: 0          IO Block: 4096   directory 
>Device: ca20h/51744d    Inode: 58346422    Links: 2 
>Access: (0777/drwxrwxrwx)  Uid: ( 1100/   codio)   Gid: ( 1100/   codio)

**Comment by Pierstoval** [comment] 2015-03-31 14:04
I think that there is an error in installation and that the installer cannot do the cleanup.
 
It seems that the principal error comes from [this line](https://github.com/symfony/symfony-installer/blob/v1.0.2/src/Symfony/Installer/DownloadCommand.php#L173)

**Comment by gander** [comment] 2015-03-31 14:05
>*Pierstoval*:
>It's not normal that the installer tries to delete this directory :confused:

No Installer, Distill:
https://github.com/raulfraile/distill/blob/v0.9.8/src/Distill.php#L223

**Comment by Pierstoval** [comment] 2015-03-31 14:06
This is some kind of unexpected behavior, I'm trying to find out but as I can't reproduce the bug, it's kinda hard... :confused:

**Comment by stof** [comment] 2015-03-31 14:13
Well, creating the folder in the installer allows to make the installation much faster than copying the content of the folder to the existing one (I'm talking about being 12x faster here on some systems).

@Pierstoval distill could detect that the path is a symlink to another folder and remove the symlink target instead before recreating by renaming the extracted content. this way, the symlink would stay there and link to the folder with the content in it

**Comment by gander** [comment] 2015-03-31 14:20
@stof It would be good if Distil detect a catalog, which can not be removed, and then copy the files and do not throw an exception.

**Comment by Pierstoval** [comment] 2015-03-31 14:43
In fact, @stof is totally right.
 
The directory specified as argument is removed by Distll because it's replaced by the one that was created by the downloader, in the temporary directory. So if the directory is a symlink, it's replaced by a normal directory.
 
To solve this issue, @gander , you can still run `symfony new ~/workspace/symfony && mv ~/workspace/symfony/* ~/workspace/ && mv ~/workspace/symfony/.* ~/workspace` to force the symfony application to be installed right into the `workspace` directory.
 
Maybe we could change the docs about it, and specify that it's mandatory to specify an empty directory name, and not a symlink...
 
As this is a Distill issue, I think we may close the issue soon.

**Comment by javiereguiluz** [comment] 2015-03-31 14:48
@Pierstoval what about triggering an exception in case a symlink is passed to the command?

**Comment by stof** [comment] 2015-03-31 14:49
@Pierstoval @javiereguiluz  Distill could be smart about the case where the directory is a symlink, by using the target of the symlink as I suggested above.

Btw, for people wanting to follow this, the case of symlinks is mentionned in https://github.com/symfony/symfony-installer/issues/130

**Comment by Pierstoval** [comment] 2015-03-31 14:55
@javiereguiluz I don't think that triggering an exception sounds good, because some people would effectively need to install the app under a symlink. Maybe we could try to add a "wrapper" that checks *at first* if the directory is a symlink, and if it is, change the final directory to make it a symlink when the process of extracting/preparing is over. It might be some kind of bad "hack", but it may work :confused:

**Comment by javiereguiluz** [comment] 2017-12-26 16:44
Closing this 3-year old issue because of the lack of activity and because Symfony Flex has made the Symfony Installer obsolete, so there's no need to fix this. Thanks!

**Closed by javiereguiluz** 2017-12-26 16:44 UTC
