### ISSUE TITLE
Installer do nothing

### ISSUE THREAD

**Issue by Valoutre** [symfony/symfony-installer#178] opened 2015-07-24 14:58 UTC
When I try to run the command `php symfony` or anything else on Windows, nothing happen and my cmd is stuck until i use Ctrl-C.

**Comment by javiereguiluz** [comment] 2015-07-24 15:07
@Valoutre I'm really sorry for these issues. The Symfony Installer is compatible with Windows and lots of Windows developers are happily using it. The experience is not as smooth as in Linux/Mac, but we are aware of it and we're trying to improve it.

Regarding this issue, we definitely need more information to spot the cause of the error. You don't see any output when executing the `symfony new my_project` command? Can you try executing the `symfony demo` command? Can you try executing those commands with the `-v` flag to show more information? Thanks.

**Comment by xabbuh** [comment] 2015-07-24 15:07
Someone [posted a solution](https://github.com/symfony/symfony-installer/issues/151#issuecomment-124044930) that worked for them on Arch Linux yesterday. Maybe this is helpful for you too.

**Comment by Valoutre** [comment] 2015-07-24 15:07
I found the solution, debug mode of my PHPStorm was activated. My bad...

**Comment by javiereguiluz** [comment] 2015-07-24 15:09
Great! I'm closing it as "fixed" then.

PS: when using Windows the installer is a bit slower than other operating systems, specially when uncompressing the downloaded Symfony files. We're working on improving it and we hope to finish it for the next stable release.

**Closed by javiereguiluz** 2015-07-24 15:09 UTC
Labels: bug, unconfirmed
