### ISSUE TITLE
Symfony installer, installs 2.6.* version of app.

### ISSUE THREAD

**Issue by sargath** [symfony/symfony-installer#165] opened 2015-06-05 12:20 UTC
Hi Guys,

Symfony installer, installs 2.6.* version of app but in repository demo has 2.7 version.
BR

**Comment by Pierstoval** [comment] 2015-06-05 12:25
It's strange, because the installer automatically installs the `latest` version, and according to [versions.json](http://symfony.com/versions.json) , the latest is `2.7.0`...
Can you run `symfony -V` to check the installer version is correct ?

**Comment by sargath** [comment] 2015-06-05 12:34
Symfony Installer version 1.1.3

**Comment by stof** [comment] 2015-06-05 12:35
maybe symfony.com does not yet use the 2.7 version for the latest.zip archive. @javiereguiluz can you check this ?

**Comment by javiereguiluz** [comment] 2015-06-05 12:46
Sadly I can't reproduce this error. Everything works right for me with the 1.1.3 installer version and the 2.7 Symfony version:

![symfony_installer](https://cloud.githubusercontent.com/assets/73419/8006164/7d1195a8-0b91-11e5-8071-11c78107e213.gif)

**Comment by sargath** [comment] 2015-06-05 12:47
@javiereguiluz  Project is oK , but check symfony demo.Problem is with demo application

**Comment by javiereguiluz** [comment] 2015-06-05 12:49
OK. The `symfony-demo` package hasn't been updated to 2.7 yet because of an error in one of our servers. I reported the issue this morning so I guess it will be fixed soon.

**Comment by javiereguiluz** [comment] 2015-06-10 07:05
Closing it as `fixed` because the demo application has been updated to 2.7 and it's available when executing the `symfony demo` command.

**Closed by javiereguiluz** 2015-06-10 07:05 UTC
Labels: bug
