### ISSUE TITLE
composer.json is Empty after instalation of Symfony

### ISSUE THREAD

**Issue by sinner** [symfony/symfony-installer#190] opened 2015-10-24 15:24 UTC
composer.json file is empty after instalation of Symfony Standar Edition 2.7.

I run on the terminal:

```sh
symfony new proyectName
```

The version I used was 1.1.7

OS: Windows 10

Solution: Change to Linux :+1: I switched to Ubuntu

**Comment by WouterJ** [comment] 2015-10-27 17:28
This bug doesn't occur on Windows 8.1. I'll debug it later today on a Windows 10 PC.

**Comment by WouterJ** [comment] 2015-10-27 21:38
I can't reproduce this on Windows 10. Everything works like it should.

**Comment by xabbuh** [comment] 2015-10-27 22:09
@WouterJ Does the behaviour change when you require `2.7.5` explicitly (maybe the issue is resolved with the build of the new release and only the archive for the version before was broken).

**Comment by senenh** [comment] 2015-10-28 16:38
@WouterJ  Is there any way I can help you seeing that it does not create the composer properly for me?

**Comment by xabbuh** [comment] 2015-10-28 16:44
@senenh Can you paste the complete output of the installer?

**Comment by senenh** [comment] 2015-10-28 16:54
@xabbuh 

Do you men this?:

c:\Apache24\htdocs>php symfony new test

 Downloading Symfony...

 Preparing project...

 OK  Symfony 2.7.6 was successfully installed. Now you can:

    * Change your current directory to C:\Apache24\htdocs\test

    * Configure your application in app/config/parameters.yml file.

    * Run your application:
        1. Execute the php app/console server:run command.
        2. Browse to the http://localhost:8000 URL.

    * Read the documentation at http://symfony.com/doc

**Comment by WouterJ** [comment] 2015-10-28 17:34
Hmm, the archives on symfony.com contain the proper composer.json files, so that's not the problem.

@sinner can you maybe check this project out locally (it's easier to debug):
```
C:\Apache24\htdocs> git clone http://github.com/symfony/symfony-installer
```
And then add some debug lines in thsi method: https://github.com/symfony/symfony-installer/blob/master/src/Symfony/Installer/NewCommand.php#L327-L361 (espescially the contents of `$contents` and the `json_encode` function injected into `file_put_contents`). And then execute the locally checked out installer:
```
C:\Apache24\htdocs> php symfony-installer/symfony new test
```

I wonder what's making the file empty and, unless I'm missing something, that's the only method editing this file.

**Comment by senenh** [comment] 2015-10-29 11:23
Now I get the following. Maybe is something easy but I'm little lost with this error.

c:\Apache24\htdocs>php symfony-installer/symfony new test1

 Downloading Symfony...




  [GuzzleHttp\Exception\RequestException]
  No system CA bundle could be found in any of the the common system location
  s.
  PHP versions earlier than 5.6 are not properly configured to use the system
  's
  CA bundle by default. In order to verify peer certificates, you will need t
  o
  supply the path on disk to a certificate bundle to the 'verify' request
  option: http://docs.guzzlephp.org/en/latest/clients.html#verify. If you do
  not
  need a specific certificate bundle, then Mozilla provides a commonly used C
  A
  bundle which can be downloaded here (provided by the maintainer of cURL):
  https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt. On
  ce
  you have a CA bundle available on disk, you can set the 'openssl.cafile' PH
  P
  ini setting to point to the path to the file, allowing you to omit the 'ver
  ify'
  request option. See http://curl.haxx.se/docs/sslcerts.html for more
  information.






  [RuntimeException]
  No system CA bundle could be found in any of the the common system location
  s.
  PHP versions earlier than 5.6 are not properly configured to use the system
  's
  CA bundle by default. In order to verify peer certificates, you will need t
  o
  supply the path on disk to a certificate bundle to the 'verify' request
  option: http://docs.guzzlephp.org/en/latest/clients.html#verify. If you do
  not
  need a specific certificate bundle, then Mozilla provides a commonly used C
  A
  bundle which can be downloaded here (provided by the maintainer of cURL):
  https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt. On
  ce
  you have a CA bundle available on disk, you can set the 'openssl.cafile' PH
  P
  ini setting to point to the path to the file, allowing you to omit the 'ver
  ify'
  request option. See http://curl.haxx.se/docs/sslcerts.html for more
  information.



new <directory> [<version>]

**Comment by cccm62** [comment] 2015-11-16 10:27
Hi,

I got the same issue

It appearsthat **json_encode** fails due to charset error:

    `$this->generateComposerProjectName();`

returns... for me `cÚdric/test4`

Shouldn't `fixComposerPackageName` encode or replace accented / special characters?

**Comment by Pierstoval** [comment] 2015-11-16 11:09
If this effectively comes from `json_encode` then yes, `fixComposerPackageName` should fix encoding errors.

**Comment by JustBlackBird** [comment] 2016-09-26 10:53
Faced the same issue on Win7. Is there any progress on it?

**Closed** 2016-10-05 09:35 UTC
