### ISSUE TITLE
symfony new command causes fatal error with PHP 7.0.0RC3

### ISSUE THREAD

**Issue by izanagisan** [symfony/symfony-installer#186] opened 2015-10-04 15:13 UTC
similarly to https://github.com/symfony/symfony-installer/issues/181 when I execute the command

    symfony new testapp

with **PHP 7.0.0RC3** I get this error and stacktrace

```
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to GuzzleHttp\Adapter\StreamAdapter::createResponseObject() must be of the type array, null given, called 
in phar:///usr/local/bin/symfony/vendor/guzzlehttp/guzzle/src/Adapter/StreamAdapter.php on line 67 and defined in phar:///usr/local/bin/symfony/vendor/guzzlehttp/
guzzle/src/Adapter/StreamAdapter.php:71
Stack trace:
#0 phar:///usr/local/bin/symfony/vendor/guzzlehttp/guzzle/src/Adapter/StreamAdapter.php(67): GuzzleHttp\Adapter\StreamAdapter->createResponseObject(Object(GuzzleH
ttp\Message\Request), NULL, Object(GuzzleHttp\Adapter\Transaction), Object(GuzzleHttp\Stream\Stream))
#1 phar:///usr/local/bin/symfony/vendor/guzzlehttp/guzzle/src/Adapter/StreamAdapter.php(52): GuzzleHttp\Adapter\StreamAdapter->createResponse(Object(GuzzleHttp\Ad
apter\Transaction))
#2 phar:///usr/local/bin/symfony/vendor/guzzlehttp/guzzle/src/Client.php(193): GuzzleHttp\Adapter\StreamAdapter->send(Object(GuzzleHttp\Adapter\Transaction))
#3 phar:///usr/local/bin/symfony/vendor/guzzlehttp/guzzle/src in phar:///usr/local/bin/symfony/vendor/guzzlehttp/guzzle/src/Adapter/StreamAdapter.php on line 71
```

thanks!

**Comment by javiereguiluz** [comment] 2015-10-04 15:21
@izanagisan this fix has been solved when upgrading Guzzle dependency. We've released the new Symfony Installer version ... but somehow there was an error publishing that version. I'm going to retry to publish the new version so you can do `symfony self-update` and get the new 1.2.0 version.

**Comment by izanagisan** [comment] 2015-10-04 15:23
thank you very much. I did see https://github.com/symfony/symfony-installer/pull/182 but guessed there was some trouble somewhere.

**Comment by javiereguiluz** [comment] 2015-10-04 15:34
I can confirm that there is an error in the task that creates the Symfony Installer package for each new release. We're into it, but right now I cannot estimate when will it be fixed.

**Comment by naroga** [comment] 2015-10-15 12:05
I too am encountering this issue (with PHP 7.0.0, RC5, released today). Waiting for the fix.

Meanwhile, @izanagisan, you can `composer create-project symfony/framework-standard-edition my_project_name`.

**Comment by javiereguiluz** [comment] 2015-10-15 14:00
I'm really sorry about this. I've asked several times to several different people at SensioLabs, but I'm still waiting. I wish I could fix this myself, but I can't.

**Comment by naroga** [comment] 2015-10-19 15:35
@javiereguiluz, FYI, cloning this repository and replacing the `symfony` symlink (at /usr/local/bin) by a new symlink pointing to this repository fixes the issue. The error has been fixed, it just hasn't been merged to the latest stable version yet.

**Comment by javiereguiluz** [comment] 2015-10-19 15:40
@naroga yes you are right. I was referring to the error that prevent us from releasing new versions of the installer :cry:

**Comment by javiereguiluz** [comment] 2015-11-16 15:44
The new version of the installer was finally published a few days ago (you can get it executing `symfony self-update`). That's why I'm closing this issue as "fixed", but feel free to reopen it if the issue is not really fixed. Thanks.

**Closed** 2015-11-16 15:44 UTC
Labels: bug
