### ISSUE TITLE
Allow installing different version of the demo

### ISSUE THREAD

**Issue by c33s** [symfony/symfony-installer#288] opened 2016-11-25 14:59 UTC
as the symfony demo evolves, removing assetic, removing swiftmailer, ... it would be handy to force to install a specific version of the demo. currently it is only possible to install the latest demo app with `demo [<directory>]`

it would be awesome to allow to install a specific version of the demo app:

`demo [<directory>] [version]`

**Comment by piotrgradzinski** [comment] 2017-11-22 10:25
Guys, I would like to bump this up. 

I find this feature useful because many time I faced the need to play with the demo not in the most recent version. 

Before taking any further steps would be great to hear your opinion. 

I think this feature is doable but requires few things. First of all under get.symfony.com/Symfony_Demo.zip we have only newest release of demo. So other releases should be uploaded as well. Second, not that easy part, is to prepare some sort of mapping between Symfony release and Demo release. For example Symfony Demo 1.0.5 corresponds with Symfony 3.3.6 dependencies. 

The desire functionality would be to install for example `demo foo 3.3`, etc. 

Thanks for your feedback!

**Comment by Pierstoval** [comment] 2017-11-22 14:31
Contrary to the Standard Edition, I'm not sure it's really useful to be able to install lower versions of the Demo.

The SE is nice to have when dealing with older Symfony versions because it helps reproducing bugs in lower versions.

The demo is more a showcase and a list of guidelines, therefore having the latest best practices sounds like the best deal to me

**Comment by piotrgradzinski** [comment] 2017-12-01 11:33
@Pierstoval - you're right. On the other hand if you really need to get older version of the demo you can just download proper tag from the repository.

**Comment by c33s** [comment] 2017-12-01 15:07
@piotrgradzinski then we won't need the symfony installer either. you can download the right symfony by cloning the standard edition or by using composer. the installer should help.

the DX could be enhanced and we would make things easier if the installer allow the installation of a specific version of the demo.

(if this all matters now after symfony4 is here)

**Comment by javiereguiluz** [comment] 2017-12-26 12:37
Closing as "won't fix" because now that [Symfony Flex](https://github.com/symfony/flex) replaces the Symfony Installer, we won't add new features to the installer. Thanks for understanding it.

**Closed by javiereguiluz** 2017-12-26 12:37 UTC
Labels: feature
